### ISSUE TITLE
The Left side menu in documentation should not link to different applications

### ISSUE THREAD

**Issue by stefreak** [syseleven/grav-docs-syseleven-stack#6]
I want to stay in the documentation system when I click main menu items

I mean

6. SysEleven Status
7. Contribution

and 

FAQ

**Comment by dschwabeS11** [comment]
FAQ is the same application, same subdomain.
6. and 7. should open new tabs though, don't know why it doesn't work currently.

Please provide more information why they should not link to different applications if it makes sense?
