### ISSUE TITLE
How can I see how my changes look like

### ISSUE THREAD

**Issue by stefreak** [syseleven/grav-docs-syseleven-stack#9]

**Comment by bashofmann** [comment]
Not sure if I understand the question correctly, either you can use the Grav Web UI at /admin, or (recommended) you just clone the repo and open it in any editor that has Markdown Support with a nice Preview Option (usually available as a Plugin), e.g. any JetBrains IDE, Sublime, VS Code:

![bildschirmfoto 2018-08-09 um 11 37 33](https://user-images.githubusercontent.com/243056/43891042-a78f1d6c-9bc8-11e8-9135-6af552927e98.png)

**Comment by stefreak** [comment]
@bashofmann cool thanks for the hint :) I indeed did not have a look at the Grav UI yet, sorry for opening stupid issues like that without informing myself in the first place.

My intention writing this was that I expected somehow to be able to render bigger changes across multiple pages to HTML to test if the change works well, before pushing it to production :)

Like I said I did not have a look yet and am sorry if it is an obvious thing if you know the UI.

**Comment by dschwabeS11** [comment]
**Hint** - Grav also has a build in PHP server (of some sort) that can do exactly that: 
https://learn.getgrav.org/basics/installation#running-grav-with-the-built-in-php-webserver-using-router-php

Therefore I close the issue. Feel free to approach us if you have further questions. :)
